const express = require("express");
const aggregationController = require("../controller/aggregation.controller");
const aggrRouter = express.Router();

aggrRouter.get("/q1", aggregationController.q1);
aggrRouter.get("/q2", aggregationController.q2);
aggrRouter.get("/q3", aggregationController.q3);
aggrRouter.get("/q4", aggregationController.q4);
aggrRouter.get("/q5", aggregationController.q5);
aggrRouter.get("/q6", aggregationController.q6);
aggrRouter.get("/q7", aggregationController.q7);
aggrRouter.get("/q8", aggregationController.q8);
aggrRouter.get("/q9", aggregationController.q9);
aggrRouter.get("/q10", aggregationController.q10);
aggrRouter.get("/q11", aggregationController.q11);
aggrRouter.get("/q12", aggregationController.q12);
aggrRouter.get("/q13", aggregationController.q13);
aggrRouter.get("/q14", aggregationController.q14);
aggrRouter.get("/q15", aggregationController.q15);
aggrRouter.get("/q16", aggregationController.q16);
aggrRouter.get("/q17", aggregationController.q17);
aggrRouter.get("/q18", aggregationController.q18);
aggrRouter.get("/q19", aggregationController.q19);
aggrRouter.get("/q20", aggregationController.q20);
aggrRouter.get("/q21", aggregationController.q21);
aggrRouter.get("/q22", aggregationController.q22);
aggrRouter.get("/q23", aggregationController.q23);
aggrRouter.get("/q24", aggregationController.q24);
aggrRouter.get("/q25", aggregationController.q25);
aggrRouter.get("/q26", aggregationController.q26);
aggrRouter.get("/q27", aggregationController.q27);
aggrRouter.get("/q28", aggregationController.q28);
aggrRouter.get("/q29", aggregationController.q29);
aggrRouter.get("/q30", aggregationController.q30);
aggrRouter.get("/q31", aggregationController.q31);
aggrRouter.get("/q32", aggregationController.q32);
aggrRouter.get("/q33", aggregationController.q33);
aggrRouter.get("/q34", aggregationController.q34);
aggrRouter.get("/q35", aggregationController.q35);
aggrRouter.get("/q36", aggregationController.q36);
aggrRouter.get("/q37", aggregationController.q37);
aggrRouter.get("/q38", aggregationController.q38);
aggrRouter.get("/q39", aggregationController.q39);
aggrRouter.get("/q40", aggregationController.q40);
aggrRouter.get("/q41", aggregationController.q41);
aggrRouter.get("/q42", aggregationController.q42);
aggrRouter.get("/q43", aggregationController.q43);
aggrRouter.get("/q44", aggregationController.q44);
aggrRouter.get("/q45", aggregationController.q45);
aggrRouter.get("/q46", aggregationController.q46);
aggrRouter.get("/q47", aggregationController.q47);
aggrRouter.get("/q48", aggregationController.q48);
aggrRouter.get("/q49", aggregationController.q49);
aggrRouter.get("/q50", aggregationController.q50);

module.exports = aggrRouter;
